# Generated by Django 5.2.5 on 2025-08-18 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-created_at'], 'verbose_name': 'Témoignage', 'verbose_name_plural': 'Témoignages'},
        ),
        migrations.AddField(
            model_name='testimonial',
            name='admin_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes administrateur'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'approbation"),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_testimonials', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='client_image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Photo du client'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='event_date',
            field=models.DateField(blank=True, null=True, verbose_name="Date de l'événement"),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='event_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Type d'événement"),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Mis en avant'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lieu'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 étoile'), (2, '2 étoiles'), (3, '3 étoiles'), (4, '4 étoiles'), (5, '5 étoiles')], default=5, verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='title',
            field=models.CharField(default=1234, max_length=200, verbose_name='Titre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='content',
            field=models.TextField(verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
    ]
